export const countries = [
  {name: 'United States', emoji: '🇺🇸', tel: '+1', code: 'US'},
  {name: 'Afghanistan', emoji: '🇦🇫', tel: '+93', code: 'AF'},
  {name: 'Albania', emoji: '🇦🇱', tel: '+355', code: 'AL'},
  {name: 'Algeria', emoji: '🇩🇿', tel: '+213', code: 'DZ'},
  {name: 'Andorra', emoji: '🇦🇩', tel: '+376', code: 'AD'},
  {name: 'Angola', emoji: '🇦🇴', tel: '+244', code: 'AO'},
  {name: 'Antigua and Barbuda', emoji: '🇦🇬', tel: '+1', code: 'AG'},
  {name: 'Argentina', emoji: '🇦🇷', tel: '+54', code: 'AR'},
  {name: 'Armenia', emoji: '🇦🇲', tel: '+374', code: 'AM'},
  {name: 'Australia', emoji: '🇦🇺', tel: '+61', code: 'AU'},
  {name: 'Austria', emoji: '🇦🇹', tel: '+43', code: 'AT'},
  {name: 'Azerbaijan', emoji: '🇦🇿', tel: '+994', code: 'AZ'},
  {name: 'Bahamas', emoji: '🇧🇸', tel: '+1', code: 'BS'},
  {name: 'Bahrain', emoji: '🇧🇭', tel: '+973', code: 'BH'},
  {name: 'Bangladesh', emoji: '🇧🇩', tel: '+880', code: 'BD'},
  {name: 'Barbados', emoji: '🇧🇧', tel: '+1', code: 'BB'},
  {name: 'Belarus', emoji: '🇧🇾', tel: '+375', code: 'BY'},
  {name: 'Belgium', emoji: '🇧🇪', tel: '+32', code: 'BE'},
  {name: 'Belize', emoji: '🇧🇿', tel: '+501', code: 'BZ'},
  {name: 'Benin', emoji: '🇧🇯', tel: '+229', code: 'BJ'},
  {name: 'Bhutan', emoji: '🇧🇹', tel: '+975', code: 'BT'},
  {name: 'Bolivia', emoji: '🇧🇴', tel: '+591', code: 'BO'},
  {name: 'Bosnia and Herzegovina', emoji: '🇧🇦', tel: '+387', code: 'BA'},
  {name: 'Botswana', emoji: '🇧🇼', tel: '+267', code: 'BW'},
  {name: 'Brazil', emoji: '🇧🇷', tel: '+55', code: 'BR'},
  {name: 'Brunei', emoji: '🇧🇳', tel: '+673', code: 'BN'},
  {name: 'Bulgaria', emoji: '🇧🇬', tel: '+359', code: 'BG'},
  {name: 'Burkina Faso', emoji: '🇧🇫', tel: '+226', code: 'BF'},
  {name: 'Burundi', emoji: '🇧🇮', tel: '+257', code: 'BI'},
  {name: 'Cabo Verde', emoji: '🇨🇻', tel: '+238', code: 'CV'},
  {name: 'Canada', emoji: '🇨🇦', tel: '+1', code: 'CA'},
  {name: 'Cambodia', emoji: '🇰🇭', tel: '+855', code: 'KH'},
  {name: 'Cameroon', emoji: '🇨🇲', tel: '+237', code: 'CM'},
  {name: 'Central African Republic', emoji: '🇨🇫', tel: '+236', code: 'CF'},
  {name: 'Chad', emoji: '🇹🇩', tel: '+235', code: 'TD'},
  {name: 'Chile', emoji: '🇨🇱', tel: '+56', code: 'CL'},
  {name: 'China', emoji: '🇨🇳', tel: '+86', code: 'CN'},
  {name: 'Colombia', emoji: '🇨🇴', tel: '+57', code: 'CO'},
  {name: 'Comoros', emoji: '🇰🇲', tel: '+269', code: 'KM'},
  {name: 'Congo', emoji: '🇨🇬', tel: '+242', code: 'CG'},
  {name: 'Costa Rica', emoji: '🇨🇷', tel: '+506', code: 'CR'},
  {name: "Côte d'Ivoire", emoji: '🇨🇮', tel: '+225', code: 'CI'},
  {name: 'Croatia', emoji: '🇭🇷', tel: '+385', code: 'HR'},
  {name: 'Cuba', emoji: '🇨🇺', tel: '+53', code: 'CU'},
  {name: 'Cyprus', emoji: '🇨🇾', tel: '+357', code: 'CY'},
  {name: 'Czech Republic', emoji: '🇨🇿', tel: '+420', code: 'CZ'},
  {name: 'Denmark', emoji: '🇩🇰', tel: '+45', code: 'DK'},
  {name: 'Djibouti', emoji: '🇩🇯', tel: '+253', code: 'DJ'},
  {name: 'Dominica', emoji: '🇩🇲', tel: '+1', code: 'DM'},
  {name: 'Dominican Republic', emoji: '🇩🇴', tel: '+1', code: 'DO'},
  {name: 'Ecuador', emoji: '🇪🇨', tel: '+593', code: 'EC'},
  {name: 'Egypt', emoji: '🇪🇬', tel: '+20', code: 'EG'},
  {name: 'El Salvador', emoji: '🇸🇻', tel: '+503', code: 'SV'},
  {name: 'Equatorial Guinea', emoji: '🇬🇶', tel: '+240', code: 'GQ'},
  {name: 'Eritrea', emoji: '🇪🇷', tel: '+291', code: 'ER'},
  {name: 'Estonia', emoji: '🇪🇪', tel: '+372', code: 'EE'},
  {name: 'Eswatini', emoji: '🇸🇿', tel: '+268', code: 'SZ'},
  {name: 'Ethiopia', emoji: '🇪🇹', tel: '+251', code: 'ET'},
  {name: 'Fiji', emoji: '🇫🇯', tel: '+679', code: 'FJ'},
  {name: 'Finland', emoji: '🇫🇮', tel: '+358', code: 'FI'},
  {name: 'France', emoji: '🇫🇷', tel: '+33', code: 'FR'},
  {name: 'Gabon', emoji: '🇬🇦', tel: '+241', code: 'GA'},
  {name: 'Gambia', emoji: '🇬🇲', tel: '+220', code: 'GM'},
  {name: 'Georgia', emoji: '🇬🇪', tel: '+995', code: 'GE'},
  {name: 'Germany', emoji: '🇩🇪', tel: '+49', code: 'DE'},
  {name: 'Ghana', emoji: '🇬🇭', tel: '+233', code: 'GH'},
  {name: 'Greece', emoji: '🇬🇷', tel: '+30', code: 'GR'},
  {name: 'Grenada', emoji: '🇬🇩', tel: '+1', code: 'GD'},
  {name: 'Guatemala', emoji: '🇬🇹', tel: '+502', code: 'GT'},
  {name: 'Guinea', emoji: '🇬🇳', tel: '+224', code: 'GN'},
  {name: 'Guinea-Bissau', emoji: '🇬🇼', tel: '+245', code: 'GW'},
  {name: 'Guyana', emoji: '🇬🇾', tel: '+592', code: 'GY'},
  {name: 'Haiti', emoji: '🇭🇹', tel: '+509', code: 'HT'},
  {name: 'Honduras', emoji: '🇭🇳', tel: '+504', code: 'HN'},
  {name: 'Hungary', emoji: '🇭🇺', tel: '+36', code: 'HU'},
  {name: 'Iceland', emoji: '🇮🇸', tel: '+354', code: 'IS'},
  {name: 'India', emoji: '🇮🇳', tel: '+91', code: 'IN'},
  {name: 'Indonesia', emoji: '🇮🇩', tel: '+62', code: 'ID'},
  {name: 'Iran', emoji: '🇮🇷', tel: '+98', code: 'IR'},
  {name: 'Iraq', emoji: '🇮🇶', tel: '+964', code: 'IQ'},
  {name: 'Ireland', emoji: '🇮🇪', tel: '+353', code: 'IE'},
  {name: 'Israel', emoji: '🇮🇱', tel: '+972', code: 'IL'},
  {name: 'Italy', emoji: '🇮🇹', tel: '+39', code: 'IT'},
  {name: 'Jamaica', emoji: '🇯🇲', tel: '+1', code: 'JM'},
  {name: 'Japan', emoji: '🇯🇵', tel: '+81', code: 'JP'},
  {name: 'Jordan', emoji: '🇯🇴', tel: '+962', code: 'JO'},
  {name: 'Kazakhstan', emoji: '🇰🇿', tel: '+7', code: 'KZ'},
  {name: 'Kenya', emoji: '🇰🇪', tel: '+254', code: 'KE'},
  {name: 'Kiribati', emoji: '🇰🇮', tel: '+686', code: 'KI'},
  {name: 'Kuwait', emoji: '🇰🇼', tel: '+965', code: 'KW'},
  {name: 'Kyrgyzstan', emoji: '🇰🇬', tel: '+996', code: 'KG'},
  {name: 'Laos', emoji: '🇱🇦', tel: '+856', code: 'LA'},
  {name: 'Latvia', emoji: '🇱🇻', tel: '+371', code: 'LV'},
  {name: 'Lebanon', emoji: '🇱🇧', tel: '+961', code: 'LB'},
  {name: 'Lesotho', emoji: '🇱🇸', tel: '+266', code: 'LS'},
  {name: 'Liberia', emoji: '🇱🇷', tel: '+231', code: 'LR'},
  {name: 'Libya', emoji: '🇱🇾', tel: '+218', code: 'LY'},
  {name: 'Liechtenstein', emoji: '🇱🇮', tel: '+423', code: 'LI'},
  {name: 'Lithuania', emoji: '🇱🇹', tel: '+370', code: 'LT'},
  {name: 'Luxembourg', emoji: '🇱🇺', tel: '+352', code: 'LU'},
  {name: 'Madagascar', emoji: '🇲🇬', tel: '+261', code: 'MG'},
  {name: 'Malawi', emoji: '🇲🇼', tel: '+265', code: 'MW'},
  {name: 'Malaysia', emoji: '🇲🇾', tel: '+60', code: 'MY'},
  {name: 'Maldives', emoji: '🇲🇻', tel: '+960', code: 'MV'},
  {name: 'Mali', emoji: '🇲🇱', tel: '+223', code: 'ML'},
  {name: 'Malta', emoji: '🇲🇹', tel: '+356', code: 'MT'},
  {name: 'Marshall Islands', emoji: '🇲🇭', tel: '+692', code: 'MH'},
  {name: 'Mauritania', emoji: '🇲🇷', tel: '+222', code: 'MR'},
  {name: 'Mauritius', emoji: '🇲🇺', tel: '+230', code: 'MU'},
  {name: 'Mexico', emoji: '🇲🇽', tel: '+52', code: 'MX'},
  {name: 'Micronesia', emoji: '🇫🇲', tel: '+691', code: 'FM'},
  {name: 'Monaco', emoji: '🇲🇨', tel: '+377', code: 'MC'},
  {name: 'Mongolia', emoji: '🇲🇳', tel: '+976', code: 'MN'},
  {name: 'Montenegro', emoji: '🇲🇪', tel: '+382', code: 'ME'},
  {name: 'Morocco', emoji: '🇲🇦', tel: '+212', code: 'MA'},
  {name: 'Mozambique', emoji: '🇲🇿', tel: '+258', code: 'MZ'},
  {name: 'Myanmar', emoji: '🇲🇲', tel: '+95', code: 'MM'},
  {name: 'Namibia', emoji: '🇳🇦', tel: '+264', code: 'NA'},
  {name: 'Nauru', emoji: '🇳🇷', tel: '+674', code: 'NR'},
  {name: 'Nepal', emoji: '🇳🇵', tel: '+977', code: 'NP'},
  {name: 'Netherlands', emoji: '🇳🇱', tel: '+31', code: 'NL'},
  {name: 'New Zealand', emoji: '🇳🇿', tel: '+64', code: 'NZ'},
  {name: 'Nicaragua', emoji: '🇳🇮', tel: '+505', code: 'NI'},
  {name: 'Niger', emoji: '🇳🇪', tel: '+227', code: 'NE'},
  {name: 'Nigeria', emoji: '🇳🇬', tel: '+234', code: 'NG'},
  {name: 'North Korea', emoji: '🇰🇵', tel: '+850', code: 'KP'},
  {name: 'North Macedonia', emoji: '🇲🇰', tel: '+389', code: 'MK'},
  {name: 'Norway', emoji: '🇳🇴', tel: '+47', code: 'NO'},
  {name: 'Oman', emoji: '🇴🇲', tel: '+968', code: 'OM'},
  {name: 'Pakistan', emoji: '🇵🇰', tel: '+92', code: 'PK'},
  {name: 'Palau', emoji: '🇵🇼', tel: '+680', code: 'PW'},
  {name: 'Palestine', emoji: '🇵🇸', tel: '+970', code: 'PS'},
  {name: 'Panama', emoji: '🇵🇦', tel: '+507', code: 'PA'},
  {name: 'Papua New Guinea', emoji: '🇵🇬', tel: '+675', code: 'PG'},
  {name: 'Paraguay', emoji: '🇵🇾', tel: '+595', code: 'PY'},
  {name: 'Peru', emoji: '🇵🇪', tel: '+51', code: 'PE'},
  {name: 'Philippines', emoji: '🇵🇭', tel: '+63', code: 'PH'},
  {name: 'Poland', emoji: '🇵🇱', tel: '+48', code: 'PL'},
  {name: 'Portugal', emoji: '🇵🇹', tel: '+351', code: 'PT'},
  {name: 'Qatar', emoji: '🇶🇦', tel: '+974', code: 'QA'},
  {name: 'Republic of Moldova', emoji: '🇲🇩', tel: '+373', code: 'MD'},
  {name: 'Romania', emoji: '🇷🇴', tel: '+40', code: 'RO'},
  {name: 'Russia', emoji: '🇷🇺', tel: '+7', code: 'RU'},
  {name: 'Rwanda', emoji: '🇷🇼', tel: '+250', code: 'RW'},
  {name: 'Saint Kitts and Nevis', emoji: '🇰🇳', tel: '+1', code: 'KN'},
  {name: 'Saint Lucia', emoji: '🇱🇨', tel: '+1', code: 'LC'},
  {name: 'Samoa', emoji: '🇼🇸', tel: '+685', code: 'WS'},
  {name: 'San Marino', emoji: '🇸🇲', tel: '+378', code: 'SM'},
  {name: 'Sao Tome and Principe', emoji: '🇸🇹', tel: '+239', code: 'ST'},
  {name: 'Saudi Arabia', emoji: '🇸🇦', tel: '+966', code: 'SA'},
  {name: 'Senegal', emoji: '🇸🇳', tel: '+221', code: 'SN'},
  {name: 'Serbia', emoji: '🇷🇸', tel: '+381', code: 'RS'},
  {name: 'Seychelles', emoji: '🇸🇨', tel: '+248', code: 'SC'},
  {name: 'Sierra Leone', emoji: '🇸🇱', tel: '+232', code: 'SL'},
  {name: 'Singapore', emoji: '🇸🇬', tel: '+65', code: 'SG'},
  {name: 'Slovakia', emoji: '🇸🇰', tel: '+421', code: 'SK'},
  {name: 'Slovenia', emoji: '🇸🇮', tel: '+386', code: 'SI'},
  {name: 'Solomon Islands', emoji: '🇸🇧', tel: '+677', code: 'SB'},
  {name: 'Somalia', emoji: '🇸🇴', tel: '+252', code: 'SO'},
  {name: 'South Africa', emoji: '🇿🇦', tel: '+27', code: 'ZA'},
  {name: 'South Korea', emoji: '🇰🇷', tel: '+82', code: 'KR'},
  {name: 'South Sudan', emoji: '🇸🇸', tel: '+211', code: 'SS'},
  {name: 'Spain', emoji: '🇪🇸', tel: '+34', code: 'ES'},
  {name: 'Sri Lanka', emoji: '🇱🇰', tel: '+94', code: 'LK'},
  {name: 'Sudan', emoji: '🇸🇩', tel: '+249', code: 'SD'},
  {name: 'Suriname', emoji: '🇸🇷', tel: '+597', code: 'SR'},
  {name: 'Sweden', emoji: '🇸🇪', tel: '+46', code: 'SE'},
  {name: 'Switzerland', emoji: '🇨🇭', tel: '+41', code: 'CH'},
  {name: 'Syrian Arab Republic', emoji: '🇸🇾', tel: '+963', code: 'SY'},
  {name: 'Tajikistan', emoji: '🇹🇯', tel: '+992', code: 'TJ'},
  {name: 'Thailand', emoji: '🇹🇭', tel: '+66', code: 'TH'},
  {name: 'Timor-Leste', emoji: '🇹🇱', tel: '+670', code: 'TL'},
  {name: 'Togo', emoji: '🇹🇬', tel: '+228', code: 'TG'},
  {name: 'Tonga', emoji: '🇹🇴', tel: '+676', code: 'TO'},
  {name: 'Trinidad and Tobago', emoji: '🇹🇹', tel: '+1', code: 'TT'},
  {name: 'Tunisia', emoji: '🇹🇳', tel: '+216', code: 'TN'},
  {name: 'Turkey', emoji: '🇹🇷', tel: '+90', code: 'TR'},
  {name: 'Turkmenistan', emoji: '🇹🇲', tel: '+993', code: 'TM'},
  {name: 'Tuvalu', emoji: '🇹🇻', tel: '+688', code: 'TV'},
  {name: 'Uganda', emoji: '🇺🇬', tel: '+256', code: 'UG'},
  {name: 'Ukraine', emoji: '🇺🇦', tel: '+380', code: 'UA'},
  {name: 'United Arab Emirates', emoji: '🇦🇪', tel: '+971', code: 'AE'},
  {name: 'United Republic of Tanzania', emoji: '🇹🇿', tel: '+255', code: 'TZ'},

  {name: 'United Kingdom', emoji: '🇬🇧', tel: '+44', code: 'GB'},
  {name: 'Uruguay', emoji: '🇺🇾', tel: '+598', code: 'UY'},
  {name: 'Uzbekistan', emoji: '🇺🇿', tel: '+998', code: 'UZ'},
  {name: 'Vanuatu', emoji: '🇻🇺', tel: '+678', code: 'VU'},
  {name: 'Venezuela', emoji: '🇻🇪', tel: '+58', code: 'VE'},
  {name: 'Vietnam', emoji: '🇻🇳', tel: '+84', code: 'VN'},
  {name: 'Yemen', emoji: '🇾🇪', tel: '+967', code: 'YE'},
  {name: 'Zambia', emoji: '🇿🇲', tel: '+260', code: 'ZM'},
  {name: 'Zimbabwe', emoji: '🇿🇼', tel: '+263', code: 'ZW'},
];
